### ISSUE TITLE
Couldn't find the GMT shared library

### ISSUE THREAD

**Issue by bridgeW** [GenericMappingTools/gmt-python#181]
*Please fill out the fields below to report an error.*

## Full code/command that generated the error
fowlling the code of http://www.gmtpython.xyz/install.html
added "export GMT_LIBRARY_PATH=$HOME/anaconda3/envs/gmt-python/lib"
or added "export GMT_LIBRARY_PATH=/opt/GMT-5.4.3/lib"
## Full error message
(gmt-python) joe@wq:~$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmt
Traceback (most recent call last):
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/utils.py", line 272, in load_libgmt
    libgmt = ctypes.CDLL(libpath)
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/__init__.py", line 28, in <module>
    _begin()
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/session_management.py", line 17, in begin
    with LibGMT() as lib:
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py", line 197, in __enter__
    self.current_session = self.create_session('gmt-python-session')
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py", line 248, in create_session
    restype=ctypes.c_void_p)
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py", line 185, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/utils.py", line 280, in load_libgmt
    raise GMTCLibNotFoundError(msg)
gmt.exceptions.GMTCLibNotFoundError: Couldn't find the GMT shared library '/opt/GMT-5.4.3/lib/libgmt.so'.
Original error message:
/usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

## System information

* Operating system: Ubuntu 16.04 LTS
* Python installation :Anaconda
* Version of GMT/Python: gmt5.4.3, python3.6
* How you installed GMT/Python: 
 gmt installing: http://gmt.soest.hawaii.edu/projects/gmt/wiki/Installing
python installing: anaconda3

*If this is a **question or feature request**, delete the above lines and instead:*

* Describe the feature you desire in as much detail as possible:

* Are you willing to try to implement and maintain this feature? 
  We'll help you through the process.

**Comment by leouieda** [comment]
Hi @bridgeW, thanks for reporting!

GMT/Python only works with the current development version of GMT (the future GMT6, http://www.gmtpython.xyz/install.html#dependencies). The Python wrapper development has required many changes to the underlying GMT code so it won't work at all with GMT5. I'll try to make this more clear in the documentation.

We've been having some issues with compatibility of some shared libraries. It's a bit finicky at the moment. Sorry.

**Comment by leouieda** [comment]
Hi @bridgeW have you tried to install again following https://www.gmtpython.xyz/latest/install.html ?

**Comment by leouieda** [comment]
This has been inactive for a while and #221 might resolve this issue too. Closing for now. Let me know if it's still a problem and we can re-open.
